language: node_js
node_js:
  - "stable"

addons:
  code_climate:
    repo_token: 5138953ef0c350edd584fa2956acc139440eaf4e6f00d8355bd9ea689188c0d3

script:
  - npm run test

cache:
  npm: true
  directories:
    - node_modules

after_success: npm run coverage